apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-kziq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-kziq
    app.kubernetes.io/part-of: ci1t-43256-0073-app
  name: devfile-sample-kziq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-kziq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-kziq
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0073-tenant/ci1t-43256-0073-app/devfile-sample-kziq@sha256:47cba82a35244519740a721d60a780ea51be93aa86d583d3aed155c95debf796
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
